### ISSUE TITLE
[learning] Posting images

### ISSUE THREAD

**Issue by xuv** [michaelhelmick/python-tumblpy#29]
Hello 

Sorry to write here. No issue with your code, but a question, if I may ask. If it's a bit long, I'm sorry. 

I studied your code because I was trying to write my own tumblr API client with python-requests and I'm pretty far with it. I can authenticate and post textual posts. But when I post an image, I get an error saying: "Headers indicate a formencoded body but body was not decodable" and the tumblr API doc is not really helpful.

The tumblr doc says that the image has to be sent in a parameter called "data". With your code, this works fine:

```
photo = open('image.png', 'rb')
post = t.post('post', blog_url='myblog.tumblr.com', params={'type':'photo', 'data': photo}) 
```

But when I try similar things with python-requests alone, it doesn't work. So I've checked your code and you seem to be differentiating 'params' and 'files' but I don't understand how.

In the file api.py (lines 123-126), you write:

```
kwargs = {'data': params, 'files': files, 'allow_redirects': False}
if files:
    kwargs['params'] = params
response = func(url, **kwargs)
```

I would be very glad if you explain me what is going on here. Because I'm gessing you're doing something with the parameters that I don't understand.

Or maybe there is a way to send images that I've not yet really understood how.

Thanks a lot in advance.

**Comment by michaelhelmick** [comment]
Sorry this took so long to respond to... I suppose I never saw this. Hope it isn't too late to help you understand.

Scroll down to "Photo Posts" https://www.tumblr.com/docs/en/api/v2#posting 

You'll see that type of posts accepts `data` as the POST param and should be a binary file. Before the lines of code you posted I call `_split_params_and_files`

https://github.com/michaelhelmick/python-tumblpy/blob/master/tumblpy/helpers.py#L4

That splits up what is actually a POST param and what is a FILE

I then sent `kwargs.files` to `files` returned from that function.

So, your code is fine, you just need to move `data` outside of params.

```python
photo = open('image.png', 'rb')
post = t.post('post', blog_url='myblog.tumblr.com', params={'type':'photo'}, files={'data': photo}) 
```

That _should_ work.
