### ISSUE TITLE
Python3 error on __repr__(self)

### ISSUE THREAD

**Issue by xuv** [michaelhelmick/python-tumblpy#30]
Hello

Here's an error I get when running the library with Python 3.2.3

```
    return u'<TumblrAPI: %s>' % self.app_key
                            ^
SyntaxError: invalid syntax
```

I can solve it by removing the 'u' in front of `'<TumblrAPI: %s>'`, but not sure if that's the way to go. Or why is it throwing an error in the first place.

**Comment by michaelhelmick** [comment]
This appears to be fixed in Python 3.5.2

![screenshot 2017-02-08 21 20 29](https://cloud.githubusercontent.com/assets/352270/22766605/7f2ec922-ee44-11e6-983f-f79b8f280b63.png)
