### ISSUE TITLE
Invalid syntax when declaring object

### ISSUE THREAD

**Issue by wakawakaJ** [michaelhelmick/python-tumblpy#33]
I get an invalid syntax on the comma "," when I try to make t as shown in the explanation. t = Tumblpy(xxxxxx, xxxxx)  I'd show a screenshot instead of the x's but it has my token and such in it. Going from your profile you are really busy and I appreciate you making the program in the first place!

**Comment by michaelhelmick** [comment]
Hi @wakawakaJ 

It looks like your "," isn't an actual comma. It looks to be a different character. A skinner comma. Please copy and paste my comma to your code and see if that works

**Comment by michaelhelmick** [comment]
@wakawakaJ Did that help?
