### ISSUE TITLE
[Feature] Proxies support

### ISSUE THREAD

**Issue by jeflopo** [michaelhelmick/python-tumblpy#36]
What do you think about adding a `proxies=None` parameter in the signature of Tumblpy class. To let the session() object connect through it ?

File changes in `apy.py`: https://github.com/michaelhelmick/python-tumblpy/commit/fa73c49da41e86e2815de79b1857f2d264c47936

It Would be ok ?

**Comment by jeflopo** [comment]
Seems that no one is maintaining this project...

**Comment by michaelhelmick** [comment]
It's maintained. Open a pull request with your change.

**Comment by jeflopo** [comment]
Done ! https://github.com/michaelhelmick/python-tumblpy/pull/37

ps. Warning - It's my very first pull request ! So, Any advice will be appreciated.
