### ISSUE TITLE
request() fails if Tumblr returns https:// URL 

### ISSUE THREAD

**Issue by patrick-brian-mooney** [michaelhelmick/python-tumblpy#39]
I'm playing with a new Tumblr blog and using Tumblpy; it took me a bit to find out why it was failing. On my new blog, 

`the_client.post('user/info')['user']['blogs'][0]['url']`

returns a secure HTTP URL; lines 112 and 113 of `api.py` fail because they're explicitly matching for 'http://'.

Currently, I'm working around it by replacing 'https://' with 'http://' in a wrapper script, which seems to work fine.

**Comment by michaelhelmick** [comment]
Sorry for the late response. Think you can test out this branch and make sure it works for your case?

https://github.com/michaelhelmick/python-tumblpy/pull/40

I'll merge and push a release if it all checks out!
