### ISSUE TITLE
Can't Reblog Posts

### ISSUE THREAD

**Issue by MaxLFarrell** [michaelhelmick/python-tumblpy#44]
Using the following:

```
t.post('post/reblog', params={'id':someid,'reblog_key':somereblog_key})
```

I get:

```
Invalid ID or reblog_key specified
```

I have double checked the reblog key on the post and the id, these are correct, however no matter what I do I get that result, I even built my own module to reblog posts in request_oauthlib!

**Comment by michaelhelmick** [comment]
Can you send over the reblog key and the blog you're trying to post to?

**Comment by MaxLFarrell** [comment]
@michaelhelmick 
'id': '148261317949'
'reblog_key': 'AmhAWZ1X'

**Comment by MaxLFarrell** [comment]
I really wonder if it has to do with the fact that the api documentation say it wants a number for the reblog key, but you can only get a str/int mix from the posts endpoint

**Comment by michaelhelmick** [comment]
@MaxLFarrell Hm, that really could be it. :/ Have you tried reaching out to any Tumblr (API?) devs on TwitteR?
