### ISSUE TITLE
Posting to secondary blog

### ISSUE THREAD

**Issue by bomb-on** [michaelhelmick/python-tumblpy#45]
Is it possible to use this library to post something to secondary blog?

I authorized the app and I took a look at Tumblr console where I picked up all the keys from. I have noticed that I can successfully post to my primary blog, but not on secondary (getting {TumblpyError} 404 'There was an error making your request.' error all the time).

This is my current code:

```
from tumblpy import Tumblpy


def post_tumblr(
        url,
        comment='',
        tags='',
        **kwargs
):
    t = Tumblpy(
        APP_KEY, APP_SECRET,
        OAUTH_TOKEN, OAUTH_TOKEN_SECRET
    )

    blog_url = t.post('user/info')
    blog_url = blog_url['user']['blogs'][0]['url']  # POSTING TO PRIMARY BLOG WORKS
    # blog_url = blog_url['user']['blogs'][1]['url']  # CANNOT POST TO SECONDARY BLOG?

    post_url = t.post(
        'post',
        blog_url=blog_url,
        params={
            'type': 'video',
            'embed': url,
            'caption': comment,
            'tags': tags,
        }
    )

    return True
```

**Comment by michaelhelmick** [comment]
Can you post to it from here: https://api.tumblr.com/console/calls/user/info

**Comment by michaelhelmick** [comment]
You'll need to put your keys in and then change the API on the right side.

**Comment by bomb-on** [comment]
Hm, but there is no "posting" functionality on Tumblr console? Or am I missing something here? :)

I got `APP_KEY`, `APP_SECRET`, `OAUTH_TOKEN` and `OAUTH_TOKEN_SECRET` in my example from the Python example on URL you posted (https://api.tumblr.com/console/calls/user/info)... As I said, it seems to work perfectly fine with posting to primary blog but I cannot get it to post to secondary.

**Comment by michaelhelmick** [comment]
What is the blog url you are trying to post to? If you don’t mind posting it here.

--
Thanks,
Mike Helmick

**Comment by bomb-on** [comment]
Yeah, no probs, it is https://wakeywakeytunes.tumblr.com/

**Comment by bomb-on** [comment]
Oh, apparently the problem behind this is pretty simple, check out the relevant [SO answer](http://stackoverflow.com/a/40941351/175793)!
If I catch some time today I might post a fix for it... ;)

**Comment by michaelhelmick** [comment]
Hm, interesting. Let me know if it works! And if it does, a fix would be great!

--
Thanks,
Mike Helmick
