### ISSUE TITLE
NameError: name 'urlparse' is not defined

### ISSUE THREAD

**Issue by mkell43** [michaelhelmick/python-tumblpy#48]
Using Python 3.5 and Python 2.7 with python-tumblpy 1.1.2 I'm getting the following error:

>   File "/home/myusername/Projects/myproject/env/lib/python3.5/site-packages/tumblpy/api.py", line 185,  in post
>    extra_endpoints=extra_endpoints, params=params)
>  File ""/home/myusername/Projects/myproject/env/lib/python3.5/site-packages/tumblpy/api.py", line 111, in request
>    blog_url = urlparse(blog_url)
> NameError: name 'urlparse' is not defined

When I did a search through api.py I did only find one reference to urlparse, and that was in the request function.  I wasn't able to find an import statement.  However, looking further I found the import references.

Changing `from .compat import json, urlencode, parse_qsl` to `from .compat import json, urlencode, parse_qsl, urlparse` seemed to clear this error, though now I'm working through figuring out an unauthorized response back from Tumblr.  So I'm not entirely sure yet this fixes everything, which is why I haven't submitted a pull request for what could be a simple fix.

**Comment by mkell43** [comment]
Update, looks like there was a commit to fix this a69aeef along with a follow up to push the version to 1.1.2 cffaf5e but even installing direct from github instead of pypi `pip install git+https://github.com/michaelhelmick/python-tumblpy.git --no-cache-dir` still seems to pull it down missing the urlparse include. :/

Am I missing something here or should I hit up stackoverflow?

That said pulling down the 1.1.0 release seemed to fix the urlparse issue (as it's previous to the code that seems to be causing it).  

`pip install git+https://github.com/michaelhelmick/python-tumblpy.git@5c7ca2335c14179c1d4568d8218053e466f6f394 --no-cache-dir`

**Comment by mobedigg** [comment]
Got fresh version from PyPi and getting same error with Python 2.7

**Comment by michaelhelmick** [comment]
https://github.com/michaelhelmick/python-tumblpy/commit/d0e39d189bf178b809114f5d9022f5108f63e688 should fix this issue (forgot to reference the issue when I committed)

`python-tumblpy 1.1.3` is available on pip
